name: lint

on: [push, pull_request]

jobs:
  stylua:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Stylua
        uses: JohnnyMorganz/stylua-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: v0.17.1
          args: --check .
