name: Lint/Style checking

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  luacheck:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        run: |
          sudo apt-get update
          sudo apt-get install luarocks
          sudo luarocks install luacheck
      - name: Run
        run: luacheck after lua init.lua

  stylua:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: JohnnyMorganz/stylua-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: v0.17.1
          args: --check .
