name: lint

on: [push, pull_request]

jobs:
  luacheck:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        run: |
          sudo apt-get update
          sudo apt-get install luarocks
          sudo luarocks install luacheck
      - name: Run
        run: luacheck --config ".luacheckrc" .

  stylua:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Stylua
        uses: JohnnyMorganz/stylua-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: v0.17.1
          args: --check .
