name: Lint/Style checking

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  selene:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: NTBBloodbath/selene-action@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: 0.25.0
          args: --display-style=quiet .

  stylua:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: JohnnyMorganz/stylua-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: v0.17.1
          args: --check .
